### PR TITLE
Add ability to build static distribution of the app

### PR DESCRIPTION
**Pull request by fix-fix**
### Rationale

Since this package is intended to help build _universal_ React apps, it should be possible to run them on client only, as well as with the both client and server.

For such apps where server-side handling is not critical, static builds add the possibility of deployment to static site hosting without server infrastructure, like github pages, and make them fully utilize CDN features.

---

### Changes

This change adds optional additional step to `build` command, that generates static document (index.html) and copies served assets to the web output folder.

The big problem was using `shared/header` module in this build step, because it happens outside of webpack context and it can't rely on global runtime variables and other preprocessing, but I managed to extract main parts into independent module inside `src/`, but there is still some duplication going on (namely `rocPath` prop). Do you have any better ideas to make it work?

Ideally it should have been done as new hook in `roc-package-web-app` with custom implementation for React, but I don't know yet how should it be composed then with descendant extensions and `roc-package-web-app` is used extensively only in `roc-package-web-app-react`.

There were also updates to some dependencies to fix peerDependencies warning.

### CODE REVIEW

**Comment by fix-fix** [comment]
Also can [list of babel plugins in roc-internal-dev](https://github.com/rocjs/roc-internal-dev/blob/0eb00f4d359aef2729c6ce8da85154146f0b3f24/commands/build.js#L3) be changed?

Right now it doesn't specify even full es2015 preset (no arrow functions, no object shorthand), and if there is code targeted for the client, UglifyJs fails with an error trying to parse es6 syntax (for example `SyntaxError: Unexpected token: operator (>)`)

**Comment by dlmr** [comment]
Thanks for the PR! I will look closer at it this weekend.

> Also can list of babel plugins in roc-internal-dev be changed?

Yes, you define a `.babelrc` in the extension that will be used when transpiling. The reason for the list that is used currently is to support the target version of Node, 4.0. When it comes to client/browser code we most often place it in `extension/app` that will be transpiled when the app is built, which also enables us to use conditional imports/requires thanks to Webpack.

> Do you have any better ideas to make it work?

As mentioned above, if the code is located in `extension/app` it will be built with Webpack with the rest of the client code.

**Comment by fix-fix** [comment]
> Yes, you define a .babelrc in the extension that will be used when transpiling.

Thanks, haven't thought of that

> As mentioned above, if the code is located in extension/app it will be built with Webpack with the rest of the client code.

I think that was my first attempt to solve this, but unfortunately action callback for `run-build-command` is not required by an app and not processed by webpack, so [exclusion from webpack externals](https://github.com/rocjs/roc-package-webpack-node/blob/df9e2f899270ef80037d783ff542d9966dbb3984/extensions/roc-package-webpack-node-dev/src/webpack/index.js#L28) doesn't help in this case.

**Comment by dlmr** [comment]
Terribly sorry for the delay.

My first thought is the way that a static build is generated. What do you think about making it a target, that is to make it possible to use it as an alternative to `web` and `node` when building.

```
roc build static
```

With this one we could then run `web` + `static` to get a site that can be statically deployed. Or just `static` to get a version of our application that has no dynamic behaviour.

This would make it possible to render the pages to static HTML to still get some benefits of server side rendering. This can be done through `ReactDOMServer.renderToStaticMarkup(element)` and can then be combined with for example https://github.com/markdalgleish/static-site-generator-webpack-plugin. We have already prepared for this a little https://github.com/rocjs/roc-package-web-app-react/blob/master/extensions/roc-package-web-app-react/src/app/server/reactRenderer.js#L172.

We would also need to manage the different ways that urls can be handled. It might for example be a good idea to have the option to toggle on ´hashHistory` when the server that is used does not fallback to the same index.html file for all requests.

I think we can avoid needing the `createHeadComponent` by using `reactRender` over `initRenderPage`.

**Comment by fix-fix** [comment]
Defining a separate build target looks interesting, I will experiment with that approach.

**Comment by fix-fix** [comment]
Superseded by rocjs/roc-package-web-app#18

**Pull request closed without merging**
