### PR TITLE
 Setting for `forceRefresh`

### LINKED ISSUE #31: Add ability to customize the options passed to `createHistory`
TL;DR: We would like a way to customize the options passed to `createHistory`.
## Background

In our hybrid apps, we run into issues when our app uses single page navigation, since the apps don't get triggers that navigation events have occurred. This causes them to behave erratically and is very annoying for the users. In these environments, we'd like to force a reload, similar to how IE9 and 10 is handled. `createBrowserHistory` allows a `forceRefresh`-option that can be used to do exactly this.
## Suggestion
- Add ability to configure the options passed to `createHistory`. These will be merged together with the `basename` option that is currently passed.
## Considerations
- `createBrowserHistory` and `createMemoryHistory` share some configuration options, such as `keyLength`, that will probably need to be the same in order to avoid hydration-issues
- Should we allow `basename` to be overridden here, or should the option in `createClient` take precedence?

### PR DESCRIPTION
**Pull request by PAkerstrand**
Allows setting `forceRefresh`-option to `browserHistory` through Roc settings.

Fixes #31.
## Discussion
- [x] Should we expose `__raw`?
- [ ] Should we pass any arguments to `forceRefresh` when it is a function?

### CODE REVIEW

**Comment by dlmr** [comment]
I do not think we need to expose/use `__raw` if we can't see the use case for changing other settings on `history`. Probably better to add it when we see a real use case for it and not add it for a potential need in the future.

Passing some arguments to the `function` might be good but I can't personally see what that should be. Maybe to the same here as for `__raw` and arguments when we see a need for it?

**Review by dlmr — APPROVED** [review]

**Comment by PAkerstrand** [comment]
@dlmr the only thing I considered passing was `FLUX_STATE`, but that requires use of SSR and Redux, which is in another conditional branch. The setting fn could grab hold of that instance for itself if needed (which would make renaming the global variable a breaking change though)

**Comment by PAkerstrand** [comment]
@dlmr seems like we get a `ECONNRESET`-error in Travis

**Comment by dlmr** [comment]
Travis have been really problematic as of late... Fixed it by restarting the build for the second time.

**Comment by dlmr** [comment]
@PAkerstrand If you do not see a need for any arguments in the function as of now I'm fine with merging this.

**Comment by PAkerstrand** [comment]
@dlmr Squash and merge?

**Pull request merged**
